services:
  - type: web
    name: reddit-scout-pro-community
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.headless=true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reddit-scout-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        # paste a Fernet key generated once locally; do NOT rotate casually
        value: REPLACE_WITH_FERNET_KEY
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false

databases:
  - name: reddit-scout-db
    plan: free
    databaseName: reddit_scout
    user: reddit_scout_user
